// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXMdGf7c0pei4-pxP072fDFVJWFJrFOYU',
    appId: '1:743837763209:web:cb4d3804b110c52da5e858',
    messagingSenderId: '743837763209',
    projectId: 'tarea8-crudfirebase-maylin',
    authDomain: 'tarea8-crudfirebase-maylin.firebaseapp.com',
    storageBucket: 'tarea8-crudfirebase-maylin.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLMBGWThXWZS5tdCG10joNuCj-guJsNYM',
    appId: '1:743837763209:android:1d9ed9e4f3523d2ea5e858',
    messagingSenderId: '743837763209',
    projectId: 'tarea8-crudfirebase-maylin',
    storageBucket: 'tarea8-crudfirebase-maylin.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZ3m5XFQH90KczcivtmmCkJfEA9G888PY',
    appId: '1:743837763209:ios:c32c2305d89b3136a5e858',
    messagingSenderId: '743837763209',
    projectId: 'tarea8-crudfirebase-maylin',
    storageBucket: 'tarea8-crudfirebase-maylin.appspot.com',
    iosBundleId: 'com.example.tarea8Crudfirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZ3m5XFQH90KczcivtmmCkJfEA9G888PY',
    appId: '1:743837763209:ios:c32c2305d89b3136a5e858',
    messagingSenderId: '743837763209',
    projectId: 'tarea8-crudfirebase-maylin',
    storageBucket: 'tarea8-crudfirebase-maylin.appspot.com',
    iosBundleId: 'com.example.tarea8Crudfirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCXMdGf7c0pei4-pxP072fDFVJWFJrFOYU',
    appId: '1:743837763209:web:579c2c42ddbe786aa5e858',
    messagingSenderId: '743837763209',
    projectId: 'tarea8-crudfirebase-maylin',
    authDomain: 'tarea8-crudfirebase-maylin.firebaseapp.com',
    storageBucket: 'tarea8-crudfirebase-maylin.appspot.com',
  );
}
